### ISSUE TITLE
Fatal error in v4.0.4: An error occurred while parsing a configuration file

### ISSUE THREAD

**Issue by tertek** [ui-icts/redcap-admin-dashboard#10]
After upgrading to 4.0.4 I am getting fatal error whenever I want to manage REDCap enabeled modules:

![image](https://user-images.githubusercontent.com/75415872/146518576-0302b744-5b5b-46ea-8514-4fa48e3b7fd5.png)

Unfortunately, I cannot upgrade to admin_dash_v4.0.5 because it is not listed in "modules available in the REDCap Repo"

![image](https://user-images.githubusercontent.com/75415872/146518776-385d563e-d0fd-42d3-a98d-aa13e1e23628.png)

This issue is rather critical, because there is no way to fix this without file access. This would be a big problem on our production server and I do not know why REDCap does not ignore invalid config...

**Comment by tertek** [comment]
Edit: I cannot update to version 4.0.5 because we are below `"framework-version": 8`

**Comment by uiowajs** [comment]
Hello,

It looks like there may be an extra comma in the config.json.  If you have access to edit the file, you could try deleting it.  It's recommended to try this on a test REDCap instance first.  

  {
      "name": "Chris Ortman",
      "email": "redcap@icts.uiowa.edu",
      "institution": "University of Iowa Institute for Clinical and Translational Science"
    },  <----- THIS ONE

Otherwise, were you able to get any other Admin Dashboard v4 versions working on REDCap 10?  Are you using LTS?  It looks like there were updates to the external module framework in 11.1.1.  Some of these newer modules may not work on older versions of REDCap.

Please let me know your thoughts.

Thanks

**Comment by tertek** [comment]
Hey,
I had to delete the module via file access. In the meanwhile a solution for this case has been posted in the REDCap community:
https://community.projectredcap.org/questions/119851/redcap-fatal-error-caused-by-invalid-external-modu.html
