### ISSUE TITLE
Backspace doesn't work when searching through reports

### ISSUE THREAD

**Issue by egoldstein-tmc** [ui-icts/redcap-admin-dashboard#2]
In version 3.4.4, when I go into a report and use the first row of text fields to search, backspace does not work, instead requiring the use of forward delete.  REDCap v8.6.5

**Comment by izneuhaus** [comment]
This was an issue some time ago that I believe has sorted itself in more recent versions of REDCap. I'm unable to replicate it on v9.3.0 or v9.4.0.

I'll leave this issue open if anyone wants to dig deeper, but otherwise the impact is minor (as far as I know) and it likely won't be a priority for me to fix.
